name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
          - name : Ubuntu
            os: ubuntu-latest
    
    name: ${{ matrix.name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
    
    - name: Setup Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update -y
        sudo apt install libwayland-dev libxkbcommon-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libgl1-mesa-dev -y

    - name: Setup Vulkan SDK
      uses: NcStudios/VulkanCI@v1.0
    
    - name: Configure CMake(Windows)
      if: matrix.os == 'windows-latest'
      run: cmake --preset=default
    
    - name: Configure CMake(Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: cmake --preset=Linux
    
    - name: Build
      run: cmake --build build